starbucks = Roaster.create(name: 'Starbucks', location: 'Seattle')
illy = Roaster.create(name: 'illy', location: 'Italy')
peets = Roaster.create(name: 'Peets Coffee', location: 'San Francisco')
philz = Roaster.create(name: 'Philz Coffee', location: 'San Francisco')
stumptown = Roaster.create(name: 'Stumptown', location: 'Portland')
blue_bottle = Roaster.create(name: 'Blue Bottle', location: 'Oakland')
cuvee = Roaster.create(name: 'Cuvee Coffee', location: 'Austin')
intelligentsia = Roaster.create(name: 'Intelligentsia Coffee', location: 'Chicago')
verve = Roaster.create(name: 'Verve', location: 'Santa Cruz')
sweet_bloom = Roaster.create(name: 'Sweet Bloom', location: 'Colorado')
caribou = Roaster.create(name: 'Caribou Coffee', location: 'Minneapolis')

pike_place = Coffee.create(name: 'Pike Place', roast: 'dark', roaster: starbucks)
big_bang = Coffee.create(name: 'Big Bang', roast: 'medium', roaster: peets)
silken_splendor = Coffee.create(name: 'Silken Splendor', roast: 'medium', roaster: philz)
philharmonic = Coffee.create(name: 'Philharmonic', roast: 'medium', roaster: philz)
hairbender = Coffee.create(name: 'Hair Bender', roast: 'dark', roaster: stumptown)
bella_donovan = Coffee.create(name: 'Bella Donovan', roast: 'dark', roaster: blue_bottle)
colombia = Coffee.create(name: 'Colombia', roast: 'medium', roaster: cuvee)
organic_french_roast = Coffee.create(name: 'Organic French Roast', roast: 'dark', roaster: intelligentsia)
sermon = Coffee.create(name: 'Sermon', roast: 'medium', roaster: verve)
hometown = Coffee.create(name: 'Hometown', roast: 'medium', roaster: sweet_bloom)
daybreak = Coffee.create(name: 'Daybreak', roast: 'light', roaster: caribou)

natasha = User.create(name: 'Natasha', email: 'natasha@email.com', password: 'password')
jessica = User.create(name: 'Jessica', email: 'jessica@email.com', password: 'password')
leeya = User.create(name: 'Leeya', email: 'leeya@email.com', password: 'password')
tiff = User.create(name: 'Tiffany',  email: 'tiff@email.com', password: 'password')
vladimir = User.create(name: 'Vladimir', email: 'vlad@email.com', password: 'password')
daniel = User.create(name: 'Daniel', email: 'daniel@email.com', password: 'password')

Brew.create(method: 'espresso')
Brew.create(method: 'drip')
Brew.create(method: 'pourover')
Brew.create(method: 'cold brew')
Brew.create(method: 'AeroPress')
Brew.create(method: 'Turkish coffee')
Brew.create(method: 'French press')

cup1 = natasha.cups.create!(brew_id: 1, coffee_id: 1, rating: Rating.create(rating: 1))
cup2 = jessica.cups.create!(brew_id: 2, coffee_id: 2, rating: Rating.create(rating: 2))
cup3 = leeya.cups.create!(brew_id: 3, coffee_id: 3, rating: Rating.create(rating: 3))
cup4 = tiff.cups.create!(brew_id: 4, coffee_id: 4, rating: Rating.create(rating: 4))
cup5 = vladimir.cups.create!(brew_id: 5, coffee_id: 5, rating: Rating.create(rating: 5))
cup6 = daniel.cups.create!(brew_id: 6, coffee_id: 6, rating: Rating.create(rating: 4))

# cup1.create_rating!(rating: 3)
# cup2.create_rating!(rating: 4)
# cup3.create_rating!(rating: 2)
# cup4.create_rating!(rating: 5)
# cup5.create_rating!(rating: 3)
# cup6.create_rating!(rating: 4)